server:
  port: 8989

spring:
  application:
    name: QUIZ-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5438/quiz?currentSchema=public&TimeZone=Asia/Kolkata
    username: fincons
    password: fincons123
    driver-class-name: org.postgresql.Driver

  jpa:  
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: mySuperSecureJwtSecretKeyThatIsAtLeast32BytesLong12345
  expiration: 3600000
